using System;
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
namespace IPA.BCFier
{
    // This file is automatically generated from the build script
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class FileVersionProvider
    {
        public static string AssemblyVersion => "2.2.6.0";
        public static string FileVersion => "2.2.6";
        public static string NuGetVersion => "2.2.6-initial-frontend0003";
        public static DateTime BuildDateUtc => new DateTime(2024, 4, 1, 20, 45, 36, DateTimeKind.Utc);
    }
}
