using System;
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
namespace IPA.Bcfier
{
    // This file is automatically generated from the build script
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class FileVersionProvider
    {
        public static string AssemblyVersion => "3.0.0.0";
        public static string FileVersion => "3.0.0";
        public static string NuGetVersion => "3.0.0-initial-frontend0010";
        public static DateTime BuildDateUtc => new DateTime(2024, 4, 2, 11, 59, 46, DateTimeKind.Utc);
    }
}
