using System;
namespace OpenProject
{
    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class VersionsService
    {
        public static string Version => "2.2.5-origin-openproje0074";
        public static string CommitInfo => "Branch.feature-openProjectBridge.Sha.6ec7c5b23495bf9e14f0e90f958b66fc5b566d28";
        public static string CommitDate => "2020-05-04";
        public static string CommitHash => "6ec7c5b23495bf9e14f0e90f958b66fc5b566d28";
        public static string InformationalVersion => "2.2.5-origin-openProjectBridge.74+Branch.feature-openProjectBridge.Sha.6ec7c5b23495bf9e14f0e90f958b66fc5b566d28";
        public static DateTime BuildDateUtc { get; } = new DateTime(2020, 5, 18, 12, 30, 26, DateTimeKind.Utc);
    }
}