// This file is automatically generated as part of the build process

export const version = {
    version: "3.0.0-initial-frontend0015",
    commitInfo: "Branch.feature-initial-frontend.Sha.87cb2be7ee14547e2da12430ebf7ca9c91d95e63",
    commitDate: "2024-04-02",
    commitHash: "87cb2be7ee14547e2da12430ebf7ca9c91d95e63",
    informationalVersion: "3.0.0-initial-frontend.15+Branch.feature-initial-frontend.Sha.87cb2be7ee14547e2da12430ebf7ca9c91d95e63",
    buildDateUtc: new Date(Date.UTC(2024, 3, 2, 19, 24, 9))
}
