using System;
namespace OpenProject.Shared
{
    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class VersionsService
    {
        public static string Version => "2.2.5-openprojectbridg0001";
        public static string CommitInfo => "2.Branch.feature-openProjectBridge.Sha.af67969b5d71cbc885b95b873411f127aeedd31c";
        public static string CommitDate => "2020-06-15";
        public static string CommitHash => "af67969b5d71cbc885b95b873411f127aeedd31c";
        public static string InformationalVersion => "2.2.5-openProjectBridge.1+2.Branch.feature-openProjectBridge.Sha.af67969b5d71cbc885b95b873411f127aeedd31c";
        public static DateTime BuildDateUtc { get; } = new DateTime(2020, 6, 22, 9, 6, 13, DateTimeKind.Utc);
    }
}